### ISSUE TITLE
Segmentation fault seemingly at random

### ISSUE THREAD

**Issue by ryan-sg** [yktoo/ymuse#27]
I have Ymuse disappear from my desktop at times, not entirely sure what gets it.  running on an up-to-date debian/bullseye (testing) system.  could it just be a version mismatch somewhere?  the `Unref.func1` line makes me think some of my go runtime or glib stuff is missing something... here is the crash dump:

```Jan 31 13:24:40 iddqd rsyslogd: rsyslogd[internal_messages]: 516 messages lost due to rate-limiting (500 allowed within 5 seconds)
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: fatal error: unexpected signal during runtime execution
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: [signal SIGSEGV: segmentation violation code=0x2 addr=0x3b070f0 pc=0x3b070f0]
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: runtime stack:
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: runtime.throw(0xa3629a, 0x2a)
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011/home/travis/.gimme/versions/go1.14.7.linux.amd64/src/runtime/panic.go:1116 +0x72
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: runtime.sigpanic()
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011/home/travis/.gimme/versions/go1.14.7.linux.amd64/src/runtime/signal_unix.go:679 +0x46a
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: goroutine 34 [syscall]:
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: runtime.cgocall(0x8cdcb0, 0xc0000486d8, 0x0)
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011/home/travis/.gimme/versions/go1.14.7.linux.amd64/src/runtime/cgocall.go:133 +0x5b fp=0xc0000486a8 sp=0xc000048670 pc=0x47a8fb
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: github.com/gotk3/gotk3/glib._Cfunc_g_object_unref(0x25abc20)
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011_cgo_gotypes.go:2967 +0x41 fp=0xc0000486d8 sp=0xc0000486a8 pc=0x561201
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: github.com/gotk3/gotk3/glib.(*Object).Unref.func1(0xc0000a21f8)
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011/home/travis/gopath/pkg/mod/github.com/gotk3/gotk3@v0.4.1-0.20200810205902-010a4368f09d/glib/glib.go:537 +0x55 fp=0xc000048710 sp=0xc0000486d8 pc=0x574f75
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: github.com/gotk3/gotk3/glib.(*Object).Unref(0xc0000a21f8)
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011/home/travis/gopath/pkg/mod/github.com/gotk3/gotk3@v0.4.1-0.20200810205902-010a4368f09d/glib/glib.go:537 +0x2b fp=0xc000048728 sp=0xc000048710 pc=0x5699fb
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: runtime.call32(0x0, 0xa5e578, 0xc0006840a0, 0x1000000010)
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011/home/travis/.gimme/versions/go1.14.7.linux.amd64/src/runtime/asm_amd64.s:539 +0x3b fp=0xc000048758 sp=0xc000048728 pc=0x4d6e8b
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: runtime.runfinq()
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011/home/travis/.gimme/versions/go1.14.7.linux.amd64/src/runtime/mfinal.go:222 +0x1df fp=0xc0000487e0 sp=0xc000048758 pc=0x48f64f
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: runtime.goexit()
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011/home/travis/.gimme/versions/go1.14.7.linux.amd64/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000487e8 sp=0xc0000487e0 pc=0x4d8be1
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: created by runtime.createfing
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011/home/travis/.gimme/versions/go1.14.7.linux.amd64/src/runtime/mfinal.go:156 +0x61
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: goroutine 1 [syscall, 2 minutes]:
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x18ac0f0, 0x0, 0x18a6090, 0x0)
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011_cgo_gotypes.go:1426 +0x4d
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: github.com/gotk3/gotk3/glib.(*Application).Run.func4(0xc000113050, 0x0, 0x0, 0x0, 0x18a6090, 0x18a6090)
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011/home/travis/gopath/pkg/mod/github.com/gotk3/gotk3@v0.4.1-0.20200810205902-010a4368f09d/glib/application.go:185 +0x94
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: github.com/gotk3/gotk3/glib.(*Application).Run(0xc000113050, 0x0, 0x0, 0x0, 0x0)
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011/home/travis/gopath/pkg/mod/github.com/gotk3/gotk3@v0.4.1-0.20200810205902-010a4368f09d/glib/application.go:185 +0x187
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: main.main()
Jan 31 13:25:37 iddqd ymuse.desktop[376864]: #011/home/travis/gopath/src/github.com/yktoo/ymuse/ymuse.go:78 +0x5d3
```

**Comment by yktoo** [comment]
Yes I'm also confronted with that every once in a while, seemingly when I play with the library and its filter. I strongly suspect the culprit is the reference management of `gotk3`, which is apparently not quite spotless. I'll try to upgrade to the latest `gotk3` master, hopefully it'll alleviate the problem.
