### ISSUE TITLE
segfault on library update

### ISSUE THREAD

**Issue by anarcat** [yktoo/ymuse#60]
i have tried this package, after installing it from Flathub (version 0.21, on Debian bullseye "stable", x11). while it was running, i tried to update a single directory with the `mpc` binary, and the whole application crashed:

```
anarcat@curie:~$ mpc update --wait 'mp3/The Kills'
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw({0xa41e95?, 0x43997b82d0?})
        /usr/lib/sdk/golang/src/runtime/panic.go:1047 +0x5d fp=0x7fffefd63c90 sp=0x7fffefd63c60 pc=0x4c28dd
runtime.sigpanic()
        /usr/lib/sdk/golang/src/runtime/signal_unix.go:819 +0x369 fp=0x7fffefd63ce0 sp=0x7fffefd63c90 pc=0x4d8309

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x8fc1e0, 0xc00012ef20)
        /usr/lib/sdk/golang/src/runtime/cgocall.go:158 +0x5c fp=0xc00012eef8 sp=0xc00012eec0 pc=0x4911dc
github.com/gotk3/gotk3/gtk._Cfunc_gtk_button_new_with_label(0x34d2280)
        _cgo_gotypes.go:6709 +0x49 fp=0xc00012ef20 sp=0xc00012eef8 pc=0x5fca09
github.com/gotk3/gotk3/gtk.ButtonNewWithLabel({0x0?, 0xc000134420?})
        /run/build/ymuse/vendor/github.com/gotk3/gotk3/gtk/gtk.go:1787 +0x67 fp=0xc00012ef80 sp=0xc00012ef20 pc=0x67a3e7
github.com/yktoo/ymuse/internal/util.NewButton({0x0?, 0xac03b8?}, {0xc00024c420, 0x13}, {0x0, 0x0}, {0xa38655, 0x12}, 0x6?)
        /run/build/ymuse/internal/util/ui-util.go:34 +0x4e fp=0xc00012efd8 sp=0xc00012ef80 pc=0x8d10ee
github.com/yktoo/ymuse/internal/player.(*MainWindow).updateLibrary(0xc00004d400)
        /run/build/ymuse/internal/player/main-window.go:2026 +0xe8a fp=0xc00012f438 sp=0xc00012efd8 pc=0x8eb82a
github.com/yktoo/ymuse/internal/player.(*MainWindow).updateLibrary-fm()
        <autogenerated>:1 +0x26 fp=0xc00012f450 sp=0xc00012f438 pc=0x8f15a6
runtime.call16(0xc00014c840, 0xc0001803d0, 0x0, 0x0, 0x0, 0x0, 0xc00012f980)
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:724 +0x49 fp=0xc00012f470 sp=0xc00012f450 pc=0x4f05a9
runtime.reflectcall(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        <autogenerated>:1 +0x3c fp=0xc00012f4b0 sp=0xc00012f470 pc=0x4f49dc
reflect.Value.call({0x94c840?, 0xc0001803d0?, 0xc00012fb08?}, {0xa2fb80, 0x4}, {0x0, 0x0, 0x3?})
        /usr/lib/sdk/golang/src/reflect/value.go:584 +0x8c5 fp=0xc00012faa0 sp=0xc00012f4b0 pc=0x5162a5
reflect.Value.Call({0x94c840?, 0xc0001803d0?, 0x13?}, {0x0?, 0x3?, 0x3?})
        /usr/lib/sdk/golang/src/reflect/value.go:368 +0xbc fp=0xc00012fb18 sp=0xc00012faa0 pc=0x51579c
github.com/gotk3/gotk3/glib.sourceFunc(0xc0000061a0?)
        /run/build/ymuse/vendor/github.com/gotk3/gotk3/glib/glib.go:324 +0xa9 fp=0xc00012fbc0 sp=0xc00012fb18 pc=0x590ce9
_cgoexp_200740c87a77_sourceFunc(0x7fffefd6474c)
        _cgo_gotypes.go:6356 +0x25 fp=0xc00012fbd8 sp=0xc00012fbc0 pc=0x5a13e5
runtime.cgocallbackg1(0x5a13c0, 0xc00012fd90?, 0x0)
        /usr/lib/sdk/golang/src/runtime/cgocall.go:316 +0x2c2 fp=0xc00012fca8 sp=0xc00012fbd8 pc=0x491702
runtime.cgocallbackg(0xc0000061a0?, 0x300000002?, 0xc0000061a0?)
        /usr/lib/sdk/golang/src/runtime/cgocall.go:235 +0x109 fp=0xc00012fd38 sp=0xc00012fca8 pc=0x491389
runtime.cgocallbackg(0x5a13c0, 0x7fffefd6474c, 0x0)
        <autogenerated>:1 +0x2f fp=0xc00012fd60 sp=0xc00012fd38 pc=0x4f45af
runtime.cgocallback(0x491205, 0x8f3890, 0xc000125df0)
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:994 +0xb4 fp=0xc00012fd88 sp=0xc00012fd60 pc=0x4f2054
runtime.systemstack_switch()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:459 fp=0xc00012fd90 sp=0xc00012fd88 pc=0x4f0060
runtime.cgocall(0x8f3890, 0xc00012fdf0)
        /usr/lib/sdk/golang/src/runtime/cgocall.go:168 +0x85 fp=0xc00012fdc8 sp=0xc00012fd90 pc=0x491205
github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x2bb60f0, 0x0, 0x2b884b0)
        _cgo_gotypes.go:1584 +0x4c fp=0xc00012fdf0 sp=0xc00012fdc8 pc=0x57b9ec
github.com/gotk3/gotk3/glib.(*Application).Run.func4(0x2b884b0?, {0x0?, 0x0, 0x2b884b0?}, 0x5?)
        /run/build/ymuse/vendor/github.com/gotk3/gotk3/glib/application.go:185 +0x7b fp=0xc00012fe30 sp=0xc00012fdf0 pc=0x5870bb
github.com/gotk3/gotk3/glib.(*Application).Run(0xa36ac8?, {0x0?, 0x0, 0x0})
        /run/build/ymuse/vendor/github.com/gotk3/gotk3/glib/application.go:185 +0xe9 fp=0xc00012fef0 sp=0xc00012fe30 pc=0x586f49
main.main()
        /run/build/ymuse/ymuse.go:75 +0x3ee fp=0xc00012ff80 sp=0xc00012fef0 pc=0x8f31ae
runtime.main()
        /usr/lib/sdk/golang/src/runtime/proc.go:250 +0x212 fp=0xc00012ffe0 sp=0xc00012ff80 pc=0x4c5132
runtime.goexit()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00012ffe8 sp=0xc00012ffe0 pc=0x4f2281

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/sdk/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000048fb0 sp=0xc000048f90 pc=0x4c54f6
runtime.goparkunlock(...)
        /usr/lib/sdk/golang/src/runtime/proc.go:369
runtime.forcegchelper()
        /usr/lib/sdk/golang/src/runtime/proc.go:302 +0xad fp=0xc000048fe0 sp=0xc000048fb0 pc=0x4c538d
runtime.goexit()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000048fe8 sp=0xc000048fe0 pc=0x4f2281
created by runtime.init.6
        /usr/lib/sdk/golang/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/sdk/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000049790 sp=0xc000049770 pc=0x4c54f6
runtime.goparkunlock(...)
        /usr/lib/sdk/golang/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /usr/lib/sdk/golang/src/runtime/mgcsweep.go:297 +0xd7 fp=0xc0000497c8 sp=0xc000049790 pc=0x4b1f77
runtime.gcenable.func1()
        /usr/lib/sdk/golang/src/runtime/mgc.go:178 +0x26 fp=0xc0000497e0 sp=0xc0000497c8 pc=0x4a6be6
runtime.goexit()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000497e8 sp=0xc0000497e0 pc=0x4f2281
created by runtime.gcenable
        /usr/lib/sdk/golang/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc0000260e0?, 0xabd470?, 0x0?, 0x0?, 0x0?)
        /usr/lib/sdk/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000049f70 sp=0xc000049f50 pc=0x4c54f6
runtime.goparkunlock(...)
        /usr/lib/sdk/golang/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x1133020)
        /usr/lib/sdk/golang/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000049fa0 sp=0xc000049f70 pc=0x4affd3
runtime.bgscavenge(0x0?)
        /usr/lib/sdk/golang/src/runtime/mgcscavenge.go:622 +0x65 fp=0xc000049fc8 sp=0xc000049fa0 pc=0x4b05c5
runtime.gcenable.func2()
        /usr/lib/sdk/golang/src/runtime/mgc.go:179 +0x26 fp=0xc000049fe0 sp=0xc000049fc8 pc=0x4a6b86
runtime.goexit()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000049fe8 sp=0xc000049fe0 pc=0x4f2281
created by runtime.gcenable
        /usr/lib/sdk/golang/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0xa6f3c8?, 0x10?, 0x20?, 0x1000000010?)
        /usr/lib/sdk/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000059e28 sp=0xc000059e08 pc=0x4c54f6
runtime.goparkunlock(...)
        /usr/lib/sdk/golang/src/runtime/proc.go:369
runtime.runfinq()
        /usr/lib/sdk/golang/src/runtime/mfinal.go:180 +0x10f fp=0xc000059fe0 sp=0xc000059e28 pc=0x4a5cef
runtime.goexit()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000059fe8 sp=0xc000059fe0 pc=0x4f2281
created by runtime.createfing
        /usr/lib/sdk/golang/src/runtime/mfinal.go:157 +0x45

goroutine 7 [select]:
runtime.gopark(0xc00019af88?, 0x3?, 0x30?, 0xae?, 0xc00019af72?)
        /usr/lib/sdk/golang/src/runtime/proc.go:363 +0xd6 fp=0xc00019adf8 sp=0xc00019add8 pc=0x4c54f6
runtime.selectgo(0xc00019af88, 0xc00019af6c, 0x0?, 0x0, 0x1?, 0x1)
        /usr/lib/sdk/golang/src/runtime/select.go:328 +0x7bc fp=0xc00019af38 sp=0xc00019adf8 pc=0x4d485c
github.com/yktoo/ymuse/internal/player.(*Connector).connect(0xc00014e000)
        /run/build/ymuse/internal/player/connector.go:170 +0xe9 fp=0xc00019afc8 sp=0xc00019af38 pc=0x8d7249
github.com/yktoo/ymuse/internal/player.(*Connector).Start.func1()
        /run/build/ymuse/internal/player/connector.go:73 +0x26 fp=0xc00019afe0 sp=0xc00019afc8 pc=0x8d6786
runtime.goexit()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00019afe8 sp=0xc00019afe0 pc=0x4f2281
created by github.com/yktoo/ymuse/internal/player.(*Connector).Start
        /run/build/ymuse/internal/player/connector.go:73 +0xcc

goroutine 8 [select]:
runtime.gopark(0xc000056f78?, 0x4?, 0xc0?, 0x34?, 0xc000056ed0?)
        /usr/lib/sdk/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000056d20 sp=0xc000056d00 pc=0x4c54f6
runtime.selectgo(0xc000056f78, 0xc000056ec8, 0xc000021280?, 0x0, 0x0?, 0x1)
        /usr/lib/sdk/golang/src/runtime/select.go:328 +0x7bc fp=0xc000056e60 sp=0xc000056d20 pc=0x4d485c
github.com/yktoo/ymuse/internal/player.(*Connector).watch(0xc00014e000)
        /run/build/ymuse/internal/player/connector.go:293 +0x167 fp=0xc000056fc8 sp=0xc000056e60 pc=0x8d7cc7
github.com/yktoo/ymuse/internal/player.(*Connector).Start.func2()
        /run/build/ymuse/internal/player/connector.go:76 +0x26 fp=0xc000056fe0 sp=0xc000056fc8 pc=0x8d6726
runtime.goexit()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000056fe8 sp=0xc000056fe0 pc=0x4f2281
created by github.com/yktoo/ymuse/internal/player.(*Connector).Start
        /run/build/ymuse/internal/player/connector.go:76 +0x10a

goroutine 34 [IO wait]:
runtime.gopark(0x918e92?, 0xb?, 0x0?, 0x0?, 0xf?)
        /usr/lib/sdk/golang/src/runtime/proc.go:363 +0xd6 fp=0xc00019b8d0 sp=0xc00019b8b0 pc=0x4c54f6
runtime.netpollblock(0x530e05?, 0x80?, 0x0?)
        /usr/lib/sdk/golang/src/runtime/netpoll.go:526 +0xf7 fp=0xc00019b908 sp=0xc00019b8d0 pc=0x4be117
internal/poll.runtime_pollWait(0x7f3168032e18, 0x72)
        /usr/lib/sdk/golang/src/runtime/netpoll.go:305 +0x89 fp=0xc00019b928 sp=0xc00019b908 pc=0x4ed5c9
internal/poll.(*pollDesc).wait(0xc000190100?, 0xc0000d9000?, 0x0)
        /usr/lib/sdk/golang/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc00019b950 sp=0xc00019b928 pc=0x54b4f2
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/sdk/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000190100, {0xc0000d9000, 0x1000, 0x1000})
        /usr/lib/sdk/golang/src/internal/poll/fd_unix.go:167 +0x25a fp=0xc00019b9d0 sp=0xc00019b950 pc=0x54c85a
net.(*netFD).Read(0xc000190100, {0xc0000d9000?, 0x4cc8a5?, 0xc000142340?})
        /usr/lib/sdk/golang/src/net/fd_posix.go:55 +0x29 fp=0xc00019ba18 sp=0xc00019b9d0 pc=0x83f449
net.(*conn).Read(0xc0000bc080, {0xc0000d9000?, 0xc00019ba88?, 0xc00019bae8?})
        /usr/lib/sdk/golang/src/net/net.go:183 +0x45 fp=0xc00019ba60 sp=0xc00019ba18 pc=0x84d105
bufio.(*Reader).fill(0xc0000dc360)
        /usr/lib/sdk/golang/src/bufio/bufio.go:106 +0xff fp=0xc00019ba98 sp=0xc00019ba60 pc=0x87b3df
bufio.(*Reader).ReadSlice(0xc0000dc360, 0x10?)
        /usr/lib/sdk/golang/src/bufio/bufio.go:372 +0x2f fp=0xc00019bae8 sp=0xc00019ba98 pc=0x87bfcf
bufio.(*Reader).ReadLine(0xc0000dc360)
        /usr/lib/sdk/golang/src/bufio/bufio.go:401 +0x27 fp=0xc00019bb38 sp=0xc00019bae8 pc=0x87c227
net/textproto.(*Reader).readLineSlice(0xc0000ea120)
        /usr/lib/sdk/golang/src/net/textproto/reader.go:56 +0x99 fp=0xc00019bc28 sp=0xc00019bb38 pc=0x87ea99
net/textproto.(*Reader).ReadLine(...)
        /usr/lib/sdk/golang/src/net/textproto/reader.go:37
github.com/fhs/gompd/v2/mpd.(*Client).readLine(0xc00019bd78?)
        /run/build/ymuse/vendor/github.com/fhs/gompd/v2/mpd/client.go:183 +0x30 fp=0xc00019bcf0 sp=0xc00019bc28 pc=0x8839f0
github.com/fhs/gompd/v2/mpd.(*Client).readList(0xc0000ea180?, {0xa32182?, 0x5?})
        /run/build/ymuse/vendor/github.com/fhs/gompd/v2/mpd/client.go:167 +0x85 fp=0xc00019bd88 sp=0xc00019bcf0 pc=0x883805
github.com/fhs/gompd/v2/mpd.(*Command).Strings(0xc0000121e0, {0xa32182, 0x7})
        /run/build/ymuse/vendor/github.com/fhs/gompd/v2/mpd/response.go:86 +0x15b fp=0xc00019be20 sp=0xc00019bd88 pc=0x891d9b
github.com/fhs/gompd/v2/mpd.(*Client).idle(0xc00019bf58?, {0x0?, 0x1?, 0x0?})
        /run/build/ymuse/vendor/github.com/fhs/gompd/v2/mpd/client.go:361 +0x8c fp=0xc00019be78 sp=0xc00019be20 pc=0x884a6c
github.com/fhs/gompd/v2/mpd.(*Watcher).watch(0xc00009ef90, {0x0?, 0x8d6726?, 0xc00014e000?})
        /run/build/ymuse/vendor/github.com/fhs/gompd/v2/mpd/watcher.go:46 +0xc7 fp=0xc00019bfb0 sp=0xc00019be78 pc=0x8924c7
github.com/fhs/gompd/v2/mpd.NewWatcher.func1()
        /run/build/ymuse/vendor/github.com/fhs/gompd/v2/mpd/watcher.go:36 +0x32 fp=0xc00019bfe0 sp=0xc00019bfb0 pc=0x8923d2
runtime.goexit()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00019bfe8 sp=0xc00019bfe0 pc=0x4f2281
created by github.com/fhs/gompd/v2/mpd.NewWatcher
        /run/build/ymuse/vendor/github.com/fhs/gompd/v2/mpd/watcher.go:36 +0x1f0

goroutine 35 [GC worker (idle)]:
runtime.gopark(0xc00004b780?, 0xc00018a540?, 0x0?, 0x0?, 0x2?)
        /usr/lib/sdk/golang/src/runtime/proc.go:363 +0xd6 fp=0xc00004b750 sp=0xc00004b730 pc=0x4c54f6
runtime.gcBgMarkWorker()
        /usr/lib/sdk/golang/src/runtime/mgc.go:1235 +0xf1 fp=0xc00004b7e0 sp=0xc00004b750 pc=0x4a8d31
runtime.goexit()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004b7e8 sp=0xc00004b7e0 pc=0x4f2281
created by runtime.gcBgMarkStartWorkers
        /usr/lib/sdk/golang/src/runtime/mgc.go:1159 +0x25

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x22ab10487836f?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/sdk/golang/src/runtime/proc.go:363 +0xd6 fp=0xc00004af50 sp=0xc00004af30 pc=0x4c54f6
runtime.gcBgMarkWorker()
        /usr/lib/sdk/golang/src/runtime/mgc.go:1235 +0xf1 fp=0xc00004afe0 sp=0xc00004af50 pc=0x4a8d31
runtime.goexit()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004afe8 sp=0xc00004afe0 pc=0x4f2281
created by runtime.gcBgMarkStartWorkers
        /usr/lib/sdk/golang/src/runtime/mgc.go:1159 +0x25

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x22ab10487a3b5?, 0x3?, 0x19?, 0x18?, 0x0?)
        /usr/lib/sdk/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000044750 sp=0xc000044730 pc=0x4c54f6
runtime.gcBgMarkWorker()
        /usr/lib/sdk/golang/src/runtime/mgc.go:1235 +0xf1 fp=0xc0000447e0 sp=0xc000044750 pc=0x4a8d31
runtime.goexit()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000447e8 sp=0xc0000447e0 pc=0x4f2281
created by runtime.gcBgMarkStartWorkers
        /usr/lib/sdk/golang/src/runtime/mgc.go:1159 +0x25

goroutine 10 [GC worker (idle)]:
runtime.gopark(0x22ab10480dd22?, 0xc0003a3040?, 0x18?, 0x14?, 0x0?)
        /usr/lib/sdk/golang/src/runtime/proc.go:363 +0xd6 fp=0xc00004bf50 sp=0xc00004bf30 pc=0x4c54f6
runtime.gcBgMarkWorker()
        /usr/lib/sdk/golang/src/runtime/mgc.go:1235 +0xf1 fp=0xc00004bfe0 sp=0xc00004bf50 pc=0x4a8d31
runtime.goexit()
        /usr/lib/sdk/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004bfe8 sp=0xc00004bfe0 pc=0x4f2281
created by runtime.gcBgMarkStartWorkers
        /usr/lib/sdk/golang/src/runtime/mgc.go:1159 +0x25
Jimi Hendrix - Foxy Lady
[paused]  #70/745   0:00/3:15 (0%)
volume: n/a   repeat: off   random: off   single: on    consume: off
[1]+  Termine 2               flatpak run com.yktoo.ymuse
```

**Comment by yktoo** [comment]
Did it happen once or is it a reproducible problem?

**Comment by anarcat** [comment]
I haven't been able to reproduce it on the second try, unfortunately.
-- 
There has been only one Christian.
They caught him and crucified him -- early.
                        - Mark Twain

**Comment by anarcat** [comment]
got it, thanks for the investigation! i should have looked in the closed issues, sorry...
